const projectData = [
  {
    snapshoot: 'req/todo1.png',
    projectName: 'To-Do list',
    technologies: ['HTML', 'CSS', 'JavaScript', 'GitHub', 'Ruby', 'Bootstrap'],
    description: 'This web application is made for a Microverse project',
    deskdesc: 'This web application is made for a Microverse project. It allows you to save your To-Do list in your localStorage so you can save your list without signing in.',
    live: 'https://nxn404-n.github.io/To-Do-list/src/',
    source: 'https://github.com/nxn404-n/To-Do-list',
    dot: 'req/dot.png',
    separator: 'req/sep.png',
    para: 'A web application that allows you to save your To-Do list. Build with HTML, CSS and JavaScript ',
    liveLogo: 'req/live-icon.svg',
    sourceLogo: 'req/github-blue.svg',
    frame: ['CANOPY', 'Full Stack Dev', '2023'],
    smBtnText: 'See Project',
    popPic: 'req/todo2.png',
  },
  {
    snapshoot: 'req/aws1.png',
    projectName: 'Awesome Books',
    technologies: ['HTML', 'CSS', 'JavaScript', 'GitHub', 'Ruby', 'Bootstrap'],
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essent',
    deskdesc: 'A web application that allows you to make a book list of your own. This web application allows you to add and remove books from your list. Build with HTML, CSS and JavaScript.',
    live: 'https://nxn404-n.github.io/Awesome-Books/',
    source: 'https://github.com/nxn404-n/Awesome-Books',
    dot: 'req/dot.png',
    separator: 'req/sep.png',
    para: 'A daily selection of privately personalized reads; no accounts or sign-ups required.',
    liveLogo: 'req/live-icon.svg',
    sourceLogo: 'req/github-blue.svg',
    frame: ['CANOPY', 'Full Stack Dev', '2023'],
    smBtnText: 'See Project',
    popPic: 'req/aws2.png',
  },
  {
    snapshoot: 'req/tonic.svg',
    projectName: 'Tonic',
    technologies: ['HTML', 'CSS', 'JavaScript', 'GitHub', 'Ruby', 'Bootstrap'],
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essent',
    deskdesc: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s with the releaLorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a',
    live: 'https://nxn404-n.github.io/',
    source: 'https://github.com/nxn404-n/nxn404-n.github.io',
    dot: 'req/dot.png',
    separator: 'req/sep.png',
    para: 'A daily selection of privately personalized reads; no accounts or sign-ups required.',
    liveLogo: 'req/live-icon.svg',
    sourceLogo: 'req/github-blue.svg',
    frame: ['CANOPY', 'Back End Dev', '2015'],
    smBtnText: 'See Project',
    popPic: 'req/poppic.svg',
  },
  {
    snapshoot: 'req/multi.svg',
    projectName: 'Multi-Post-Stories',
    technologies: ['HTML', 'CSS', 'JavaScript', 'GitHub', 'Ruby', 'Bootstrap'],
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essent',
    deskdesc: 'A web application that allows you to make a book list of your own. This web application allows you to add and remove books from your list. Build with HTML, CSS and JavaScript.',
    live: 'https://nxn404-n.github.io/Awesome-Books/',
    source: 'https://github.com/nxn404-n/Awesome-Books',
    dot: 'req/dot.png',
    separator: 'req/sep.png',
    para: 'A daily selection of privately personalized reads; no accounts or sign-ups required.',
    liveLogo: 'req/live-icon.svg',
    sourceLogo: 'req/github-blue.svg',
    frame: ['CANOPY', 'Back End Dev', '2015'],
    smBtnText: 'See Project',
    popPic: 'req/poppic.svg',
  },
];

export default projectData;