const projectData = [
  {
    snapshoot: 'req/tonic.svg',
    projectName: 'Tonic',
    technologies: ['HTML', 'CSS', 'JavaScript', 'GitHub', 'Ruby'],
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essent',
    live: 'https://nxn404-n.github.io/',
    source: 'https://github.com/nxn404-n/nxn404-n.github.io',
    dot: 'req/dot.png',
    separator: 'req/sep.png',
    para: 'A daily selection of privately personalized reads; no accounts or sign-ups required.',
    liveLogo: 'req/live-icon.svg',
    sourceLogo: 'req/github-blue.svg',
    frame: ['CANOPY', 'Back End Dev', '2015'],
    smBtnText: 'See Project',
    popPic: 'req/poppic.svg',
  },
  {
    snapshoot: 'req/multi.svg',
    projectName: 'Multi-Post-Stories',
    technologies: ['HTML', 'CSS', 'JavaScript', 'GitHub', 'Ruby'],
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essent',
    live: 'https://nxn404-n.github.io/',
    source: 'https://github.com/nxn404-n/nxn404-n.github.io',
    dot: 'req/dot.png',
    separator: 'req/sep.png',
    para: 'A daily selection of privately personalized reads; no accounts or sign-ups required.',
    liveLogo: 'req/live-icon.svg',
    sourceLogo: 'req/github-blue.svg',
    frame: ['CANOPY', 'Back End Dev', '2015'],
    smBtnText: 'See Project',
    popPic: 'req/poppic.svg',
  },
  {
    snapshoot: 'req/tonic.svg',
    projectName: 'Tonic',
    technologies: ['HTML', 'CSS', 'JavaScript', 'GitHub', 'Ruby'],
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essent',
    live: 'https://nxn404-n.github.io/',
    source: 'https://github.com/nxn404-n/nxn404-n.github.io',
    dot: 'req/dot.png',
    separator: 'req/sep.png',
    para: 'A daily selection of privately personalized reads; no accounts or sign-ups required.',
    liveLogo: 'req/live-icon.svg',
    sourceLogo: 'req/github-blue.svg',
    frame: ['CANOPY', 'Back End Dev', '2015'],
    smBtnText: 'See Project',
    popPic: 'req/poppic.svg',
  },
  {
    snapshoot: 'req/multi.svg',
    projectName: 'Multi-Post-Stories',
    technologies: ['HTML', 'CSS', 'JavaScript', 'GitHub', 'Ruby'],
    description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industrys standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essent',
    live: 'https://nxn404-n.github.io/',
    source: 'https://github.com/nxn404-n/nxn404-n.github.io',
    dot: 'req/dot.png',
    separator: 'req/sep.png',
    para: 'A daily selection of privately personalized reads; no accounts or sign-ups required.',
    liveLogo: 'req/live-icon.svg',
    sourceLogo: 'req/github-blue.svg',
    frame: ['CANOPY', 'Back End Dev', '2015'],
    smBtnText: 'See Project',
    popPic: 'req/poppic.svg',
  },
];

